### ISSUE TITLE
Had this running for 6 months....

### ISSUE THREAD

**Issue by gingerknowledge** [ashishtank/MMM-MercedesMe#3]
And all of a sudden, it just has the single dial (have tried to change it to dual too) and nothing in there. i.e. no miles or % showing. 

To try to self resolve, I re-setup the linkage to Mercedes, totally uninstalled and re-installed with new API's etc and still nothing. 

Anyone else have this issue or know a resolution please?

**Comment by ashishtank** [comment]
Hi @gingerknowledge 

Other user have also reported same issue. There is update in Mercedes API. I will look into it and update you once it is solved.

**Comment by gingerknowledge** [comment]
I thought it might be, I received the mail from Mercedes too so am waiting until Nov to realign my API’s. Thanks!!
